### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by VictorDiasO** [VictorDiasO/LinkerVeja-MegaHack-5.0-ReactJS#1]
## Linker Veja+
- [ ] Criar o projeto ReactJS
- [ ] Preparar o ambiente
- [ ] Instalar as dependências
- [ ] Criar conexões com um banco de dados MySQL
- [ ] Receber os inputs do usuário
